CREATE TABLE IF NOT EXISTS `users` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `links` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    originalUrl VARCHAR(255) NOT NULL,
    shortUrl VARCHAR(10) NOT NULL UNIQUE,
    clicks INT DEFAULT 0,
    userID INT
);